(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["NotifyAfter`"];


{NotifyAfter};


Begin["`Private`"];


NotifyAfter::usage = "NotifyAfter[\!\(\*
StyleBox[\"expr\",\nFontSlant->\"Italic\"]\)] evaluates \!\(\*
StyleBox[\"expr\",\nFontSlant->\"Italic\"]\), shows notification about completeness and returns the result.

Optional parameters:
 \[Bullet] \!\(\*
StyleBox[\"Beep\",\nFontSlant->\"Italic\"]\) \[Rule] True/False. Whether a sound must be played when evaluation is complete.";


Options[NotifyAfter] = {Beep -> True};


NotifyAfter[expr_, OptionsPattern[]] := Block[{res, t},
	(* Running code. *)
	{t, res} = AbsoluteTiming[expr];
	(* Creating a dialog, when we are finished. *)
	CreateDialog[
		{
			Cell[TextData[{
				"Your calculations have been completed!\n\nFile: ",
				StyleBox[Quiet@Check[NotebookFileName[], "Untitled"] <> " (" <> ToString[$Line] <> ")", FontWeight -> "Bold", FontColor -> RGBColor[0., 0.4, 0.]],
				"\nTime elapsed: ",
				StyleBox[ToString@N[t, 5], FontWeight -> "Bold", FontColor -> RGBColor[0., 0.4, 0.]],
				" s.\n\nIf you have any other pending evaluation, it is being performed right now."
			}], "Text"],
			DefaultButton[]
		},
		WindowTitle -> "Evaluation has been completed"
	];
	(* Emitting a sound. *)
	If[OptionValue[Beep],
		Beep[]
	];
	(* Returning the result. *)
	res
];


SetAttributes[NotifyAfter, {HoldFirst, Protected, ReadProtected}];


End[];


EndPackage[];
